#pragma once

#define TOMB_Main main

#ifndef TOMB_SUCCESS
#define TOMB_SUCCESS 0
#endif

#ifndef TOMB_FAILURE
#define TOMB_FAILURE 1
#endif

#ifndef TOMB_CHECK_RESULT
#define TOMB_CHECK_RESULT(x) ((x == TOMB_SUCCESS) ? 1 : 0)
#endif

#ifndef TOMB_INTERNAL
#define TOMB_INTERNAL static
#endif

#ifndef TOMB_STATIC
#define TOMB_STATIC static
#endif

#ifndef TOMB_EXTERNAL
#define TOMB_EXTERNAL extern
#endif

#ifndef TOMB_KILOBYTES_TO_BYTES
#define TOMB_KILOBYTES_TO_BYTES(x) (x * 1024ULL)
#endif

#ifndef TOMB_MEGABYTES_TO_BYTES
#define TOMB_MEGABYTES_TO_BYTES(x) (TOMB_KILOBYTES_TO_BYTES(x) * 1024ULL)
#endif

#ifndef TOMB_GIGABYTES_TO_BYTES
#define TOMB_GIGABYTES_TO_BYTES(x) (TOMB_MEGABYTES_TO_BYTES(x) * 1024ULL)
#endif

#ifndef TOMB_BYTES_TO_KILOBYTES
#define TOMB_BYTES_TO_KILOBYTES(x) (x / 1024ULL)
#endif

#ifndef TOMB_BYTES_TO_MEGABYTES
#define TOMB_BYTES_TO_MEGABYTES(x) (TOMB_BYTES_TO_KILOBYTES(x) / 1024ULL)
#endif

#ifndef TOMB_BYTES_TO_GIGABYTES
#define TOMB_BYTES_TO_GIGABYTES(x) (TOMB_BYTES_TO_GIGABYTES(x) / 1024ULL)
#endif